version: "3"

services:
  back-end:
     build: .
     container_name: back-end
     restart: always
     expose:
       - "8000"

  front-end:
    build: ./front-end/
    container_name: front-end
    restart: always
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - back-end
